server:
  port: 11300
github:
  active: prod
#    配置数据库连接信息
spring:
  datasource:
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.130:15433/postgres
common:
  sqlite:
    url: jdbc:sqlite:E:/Repertory/Sqlite/tbl_cdma_hlr
    tablename: tbl_cdma_hlr
    driver-class-name: org.sqlite.JDBC
    username:
    password:
