server:
  port: 11300
github:
  active: prod
#    配置数据库连接信息
spring:
  datasource:
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.130:15433/postgres
  data:
    redis:
      # 地址
      host: 192.168.88.130
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码(如没有密码请注释掉)
      password: 123456
      # 连接超时时间
      timeout: 10s
      # 是否开启ssl
      ssl:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    # SQL语句打印
    show-sql: true
    # 配置方言
    database-platform: org.hibernate.dialect.PostgreSQLDialect
redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${ruoyi.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 10
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50