spring:
  profiles:
    active: prod
  application:
    name: rothschil-common
  jackson:
    default-property-inclusion: non-null

  jpa:
    hibernate:
      ddl-auto: none
    # SQL语句打印
    show-sql: true
    # 配置方言
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: io.github.rothschil.**.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
rothschil:
  cache:
    prefix: rothschil
logging:
  config: classpath:logback-spring.xml
common:
  sqlite:
    url: jdbc:sqlite:E:/Repertory/Sqlite/tbl_cdma_hlr
    tablename: tbl_cdma_hlr
    driver-class-name: org.sqlite.JDBC
    username:
    password: