server:
  port: 11300
github:
  active: prod
#    配置数据库连接信息
spring:
  datasource:
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.130:15433/postgres
  cloud:
    consul: #Consul服务注册发现配置
      host: 192.168.88.130
      port: 8500
      discovery:
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /health
        service-name: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}