spring:
  profiles:
    active: prod
  application:
    name: rothschil-common
  jackson:
    default-property-inclusion: non-null

  jpa:
    hibernate:
      ddl-auto: none
    # SQL语句打印
    show-sql: true
    # 配置方言
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mybatis:
  mapper:
    #locations: classpath:com/bj/springboot/mapper/*.xml
    locations: classpath:/mapper/*.xml
rothschil:
  cache:
    prefix: rothschil
logging:
  config: classpath:logback-spring.xml