server:
  port: 11200
github:
  active: dev
spring:
  redis:
    redisson:
      config:
        singleServerConfig:
          password: 123456
          address: "redis://127.0.0.1:6379"
          database: 1
        threads: 0
        nettyThreads: 0
        codec: !<org.redisson.codec.FstCodec> {}
        transportMode: "NIO
  datasource:
    username: admin
    password: 12345678
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.130:5432/postgres?useUnicode=true&characterEncoding=utf8