server:
  port: 11300
github:
  active: prod
#    配置数据库连接信息
spring:
  datasource:
    username: admin
    password: 12345678
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.130:5432/postgres
