spring:
  profiles:
    active: prod
  application:
    name: rothschil-common

mybatis:
  mapper:
    #locations: classpath:com/bj/springboot/mapper/*.xml
    locations: classpath:/mapper/*.xml
rothschil:
  cache:
    prefix: rothschil
logging:
  config: classpath:logback-spring.xml