server:
  port: 9090
# mysql数据源配置

spring:
  application:
    name: mybatis-plus
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/au_app?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=6000
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /static/**,/templates/**
    view:
      suffix: .html
  thymeleaf:
    servlet:
      contentType: text/html; charset=utf-8
    cache: false
    mode: HTML
    encoding: UTF-8
    enabled: true
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  type-aliases-package: io.github.rothschil.demo.entity
  type-aliases-super-type: java.lang.Object